# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cart.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from protos import product_pb2 as product__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncart.proto\x12\x04\x63\x61rt\x1a\x1bgoogle/protobuf/empty.proto\x1a\rproduct.proto\"T\n\x08\x63\x61rtItem\x12\x12\n\ncartItemId\x18\x01 \x01(\t\x12\"\n\x08products\x18\x02 \x03(\x0b\x32\x10.product.product\x12\x10\n\x08quantity\x18\x03 \x01(\x05\" \n\ncartItemId\x12\x12\n\ncartItemId\x18\x01 \x01(\t2s\n\x0c\x43\x61rtServicer\x12\x32\n\x0e\x63reateCartItem\x12\x0e.cart.cartItem\x1a\x10.cart.cartItemId\x12/\n\x0bgetCartItem\x12\x10.cart.cartItemId\x1a\x0e.cart.cartItemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cart_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CARTITEM']._serialized_start=64
  _globals['_CARTITEM']._serialized_end=148
  _globals['_CARTITEMID']._serialized_start=150
  _globals['_CARTITEMID']._serialized_end=182
  _globals['_CARTSERVICER']._serialized_start=184
  _globals['_CARTSERVICER']._serialized_end=299
# @@protoc_insertion_point(module_scope)
